Server tests. #288
Together-100Devs/Together pull request #289
Opened 2023-01-25 18:28 UTC by romanstetsyk

# Description

Added Jest tests for Express middleware:

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Issue
- [x] Is this related to a specific issue? Is so please specify: #288

# Checklist:

- [x] This PR is up to date with the development branch, and merge conflicts have been resolved
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2023-02-02 03:44 UTC, MatthewBozin commented on server/test/unit/createEventsArray.test.js
> +      firstEventStart: Date.parse("2023-01-28T15:00:00.000+00:00"),
I received typeerrors in all the tests in this sequence when I tried to run it! It looks like we're trying to feed the createEventsArray function an object with the properties "firstEventStart", "firstEventEnd", and "lastEventStart" when it's expecting to receive "initialDate", "finalDate", "startTime", and "endTime".

2023-02-02 03:54 UTC, MatthewBozin commented
I went through and tried out the test suite! Everything worked except for createEventsArray (left a comment regarding this).

2023-02-02 03:57 UTC, MatthewBozin commented on server/routes/events.js
> +  // validateBody(createEventSchema),
It looks like when I uncomment these, creating an event returns a 400 error.

2023-02-02 04:01 UTC, MatthewBozin commented on client/src/features/form/FormMoverControl.js
> +        // if (endDateTime < startDateTime) {
Do we want this to remain commented out?

2023-02-02 04:06 UTC, MatthewBozin requested changes
Hey Roman! 
I tried out the test suite! All test files worked fine except for createEventsArray (left a comment regarding the likely cause). While the app works fine, I noticed you've commented out a few of the form validation checks on the client and server side and wanted to know more about that before we merge this PR.
Thanks!
-Matt

2023-02-02 12:48 UTC, romanstetsyk commented
@MatthewBozin thank you for reviewing this PR. This is a work in progress. It was made before we discovered bugs dealing with time zones and daylight-saving time. I am considering different approaches to solving this, and the tests haven't been updated yet.

2023-02-02 21:08 UTC, MatthewBozin commented
Ah gotcha! Thanks for letting me know!

2023-02-07 19:48 UTC, romanstetsyk commented
@MatthewBozin I've fixed the timezone bug (hopefully). Could you review the updated PR? We might need to add a warning when someone tries to create an event when time switches from normal to daylight-saving, as the display times may be misleading. But the most important thing is that in the database, the UTC times are saved correctly!

2023-02-15 23:05 UTC, Caleb-Cohen commented
Added [a commit](https://github.com/Together-100Devs/Together/pull/289/commits/1eb314e68f9a66aa40b35d86d8e73e35ef2042b9) please review.

2023-02-17 17:35 UTC, merged